/**
 * Seed Ethiopian commercial banks into the `bank` table.
 * Run with: node seed_ethiopian_banks.js
 */
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const BANKS = [
  {
    bank_code: 'CBE',
    bank_name: 'Commercial Bank of Ethiopia',
    swift_code: 'CBETETAA',
    address: 'Headquarters, Unity Square, Addis Ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    phone_number: '+251111551056',
    email: 'info@combanketh.et',
    website: 'https://www.combanketh.et',
    is_head_office: true,
  },
  {
    bank_code: 'AWASH',
    bank_name: 'Awash Bank S.C.',
    swift_code: 'AWINETAA',
    address: 'Awash Towers, Ras Desta Damtew St, Addis Ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    phone_number: '+251116182178',
    email: 'info@awashbank.com',
    website: 'https://www.awashbank.com',
    is_head_office: true,
  },
  {
    bank_code: 'BOA',
    bank_name: 'Bank of Abyssinia S.C.',
    swift_code: 'ABYSETAA',
    address: 'Bank of Abyssinia Bldg, Gambia St, Addis Ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    phone_number: '+251115534406',
    email: 'boa@bankofabyssinia.com',
    website: 'https://www.bankofabyssinia.com',
    is_head_office: true,
  },
  {
    bank_code: 'DASHEN',
    bank_name: 'Dashen Bank S.C.',
    swift_code: 'DASHETAL',
    address: 'Dashen Bank Bldg, Debre Zeit Road, Addis Ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    phone_number: '+251116290890',
    email: 'info@dashenbanksc.com',
    website: 'https://www.dashenbanksc.com',
    is_head_office: true,
  },
  {
    bank_code: 'WEGAGEN',
    bank_name: 'Wegagen Bank S.C.',
    swift_code: 'WEBAETAA',
    address: 'Wegagen Tower, Churchill Ave, Addis Ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    phone_number: '+251115524868',
    email: 'info@wegagenbank.com',
    website: 'https://www.wegagenbank.com',
    is_head_office: true,
  },
  {
    bank_code: 'NIB',
    bank_name: 'Nib International Bank S.C.',
    swift_code: 'NIBIETAA',
    address: 'Nib Bank Bldg, Bole Rd, Addis Ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    phone_number: '+251116393838',
    email: 'info@nibbank.et',
    website: 'https://www.nibbank.et',
    is_head_office: true,
  },
  {
    bank_code: 'CBE_OROMIA',
    bank_name: 'Cooperative Bank of Oromia S.C.',
    swift_code: 'COORETAA',
    address: 'Coopbank Bldg, Bole Sub-City, Addis Ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    phone_number: '+251116622060',
    email: 'info@coopbankoromia.com',
    website: 'https://www.coopbankoromia.com',
    is_head_office: true,
  },
  {
    bank_code: 'DBE',
    bank_name: 'Development Bank of Ethiopia',
    swift_code: 'DBEEETAA',
    address: 'DBE Headquarters, Ras Desta Damtew Ave, Addis Ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    phone_number: '+251115511188',
    email: 'info@dbe.com.et',
    website: 'https://www.dbe.com.et',
    is_head_office: true,
  },
  {
    bank_code: 'LION',
    bank_name: 'Lion International Bank S.C.',
    swift_code: null,
    address: 'Lion Bank Bldg, Kirkos Sub-City, Addis Ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    phone_number: '+251115156555',
    email: 'info@lionbanksc.com',
    website: 'https://www.lionbanksc.com',
    is_head_office: true,
  },
  {
    bank_code: 'HIBRET',
    bank_name: 'Hibret Bank (United Bank S.C.)',
    swift_code: null,
    address: 'United Bank Bldg, Arat Kilo, Addis Ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    phone_number: '+251116183100',
    email: 'info@hibretbank.com',
    website: 'https://www.hibretbank.com',
    is_head_office: true,
  },
  {
    bank_code: 'OROMIA_IB',
    bank_name: 'Oromia International Bank S.C.',
    swift_code: null,
    address: 'OIB Headquarters, Kirkos Sub-City, Addis Ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    phone_number: '+251114726400',
    email: 'info@oromiabank.com',
    website: 'https://www.oromiabank.com',
    is_head_office: true,
  },
  {
    bank_code: 'BERHAN',
    bank_name: 'Berhan Bank S.C.',
    swift_code: null,
    address: 'Berhan Bank Bldg, Bole Sub-City, Addis Ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    phone_number: '+251116632222',
    email: 'info@berhanbank.com',
    website: 'https://www.berhanbank.com',
    is_head_office: true,
  },
  {
    bank_code: 'ABAY',
    bank_name: 'Abay Bank S.C.',
    swift_code: null,
    address: 'Abay Bank Bldg, Kirkos Sub-City, Addis Ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    phone_number: '+251115571026',
    email: 'info@abaybank.com',
    website: 'https://www.abaybank.com',
    is_head_office: true,
  },
  {
    bank_code: 'ADDIS_IB',
    bank_name: 'Addis International Bank S.C.',
    swift_code: null,
    address: 'Addis Bank Bldg, Bole Sub-City, Addis Ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    phone_number: '+251116631234',
    email: 'info@addisbank.com',
    website: 'https://www.addisbank.com',
    is_head_office: true,
  },
  {
    bank_code: 'BUNNA',
    bank_name: 'Bunna International Bank S.C.',
    swift_code: null,
    address: 'Bunna Bank Bldg, Yeka Sub-City, Addis Ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    phone_number: '+251116183344',
    email: 'info@bunnabank.com',
    website: 'https://www.bunnabank.com',
    is_head_office: true,
  },
  {
    bank_code: 'ENAT',
    bank_name: 'Enat Bank S.C.',
    swift_code: null,
    address: 'Enat Bank Bldg, Bole Sub-City, Addis Ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    phone_number: '+251116293948',
    email: 'info@enatbanksc.com',
    website: 'https://www.enatbanksc.com',
    is_head_office: true,
  },
  {
    bank_code: 'GLOBAL',
    bank_name: 'Global Bank Ethiopia S.C.',
    swift_code: null,
    address: 'Global Bank Bldg, Kirkos Sub-City, Addis Ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    phone_number: '+251116629191',
    email: 'info@globalbank.com.et',
    website: 'https://www.globalbank.com.et',
    is_head_office: true,
  },
  {
    bank_code: 'AMHARA',
    bank_name: 'Amhara Bank S.C.',
    swift_code: null,
    address: 'Amhara Bank Bldg, Bahir Dar',
    city: 'Bahir Dar',
    country: 'Ethiopia',
    phone_number: '+251582203939',
    email: 'info@amharabank.et',
    website: 'https://www.amharabank.et',
    is_head_office: true,
  },
  {
    bank_code: 'TSEHAY',
    bank_name: 'Tsehay Bank S.C.',
    swift_code: null,
    address: 'Tsehay Bank Bldg, Kirkos Sub-City, Addis Ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    phone_number: '+251116631100',
    email: 'info@tsehaybank.com',
    website: null,
    is_head_office: true,
  },
  {
    bank_code: 'SIINQEE',
    bank_name: 'Siinqee Bank S.C.',
    swift_code: null,
    address: 'Siinqee Bank Bldg, Shiro Meda, Addis Ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    phone_number: '+251116630808',
    email: 'info@siinqeebank.com',
    website: null,
    is_head_office: true,
  },
  {
    bank_code: 'ZAMZAM',
    bank_name: 'ZamZam Bank S.C.',
    swift_code: null,
    address: 'ZamZam Bank Bldg, Bole Sub-City, Addis Ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    phone_number: '+251116397474',
    email: 'info@zamzambank.com',
    website: 'https://www.zamzambank.com',
    is_head_office: true,
  },
  {
    bank_code: 'GOH',
    bank_name: 'Goh Betoch Bank S.C.',
    swift_code: null,
    address: 'Goh Betoch Bank Bldg, Kirkos Sub-City, Addis Ababa',
    city: 'Addis Ababa',
    country: 'Ethiopia',
    phone_number: '+251116630900',
    email: 'info@gohbetochbank.com',
    website: null,
    is_head_office: true,
  },
];

async function main() {
  console.log('Seeding Ethiopian banks...');
  let inserted = 0;
  let skipped = 0;

  for (const bank of BANKS) {
    const existing = await prisma.bank.findUnique({ where: { bank_code: bank.bank_code } });
    if (existing) {
      console.log(`  ⏭  Skipped (already exists): ${bank.bank_name}`);
      skipped++;
      continue;
    }
    await prisma.bank.create({ data: bank });
    console.log(`  ✅ Inserted: ${bank.bank_name}`);
    inserted++;
  }

  console.log(`\nDone. Inserted: ${inserted} | Skipped: ${skipped}`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
